import { appWithTranslation } from 'next-i18next'
import '@/styles/globals.css'
import type { AppProps } from 'next/app';
import Layout from '../src/layout'
import Head from 'next/head';
// import '../i18n';


 function App({ Component, pageProps }: AppProps) {
  return (
    <>
     <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel='icon' href='../assets/logo.png' />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}
export default appWithTranslation(App)