import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel='icon' href='../public/icons/icon-48x48.png' />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h2 style={{color:'#13805D'}}>Welcome to PWA</h2>
      </main>
    </>
  )
}
